
package vistas;

import controlador.ControladorTaco;
import modelo.Alimento;
import modelo.Salsa;
import modelo.Tortilla;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Gerardo
 */
public final class FrmTaco extends javax.swing.JFrame {

    /**
     * Creates new form FrmTaco
     * 
     */
    ControladorTaco controladortaco = new ControladorTaco();
    DefaultTableModel dtmTortilla = new DefaultTableModel();
    DefaultTableModel dtmAlimento = new DefaultTableModel();
    DefaultTableModel dtmSalsa = new DefaultTableModel();
    //int[] arrayy = new int[2];
    public FrmTaco() {
        initComponents();
         estiloFrmTaco();
        numeroDeTacosAlmacenados();
        controladortaco.cargarComboboxss(comboTortilla, comboAlimentos, comboSalsa);
        estiloTablas(dtmTortilla, tblTortilla);
        estiloTablas(dtmAlimento, tblAlimentos);
        estiloTablas(dtmSalsa, tblSalsa);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTortilla6 = new javax.swing.JLabel();
        opcSimple = new javax.swing.JRadioButton();
        opcDoble = new javax.swing.JRadioButton();
        comboTortilla = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTortilla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdTaco = new javax.swing.JTextField();
        btnBuscarTaco = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbTortilla3 = new javax.swing.JLabel();
        comboAlimentos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlimentos = new javax.swing.JTable();
        lbTortilla4 = new javax.swing.JLabel();
        comboSalsa = new javax.swing.JComboBox<>();
        btnTacoEconomico = new javax.swing.JButton();
        btnTacoCaro = new javax.swing.JButton();
        btnTacoPromedio = new javax.swing.JButton();
        btnGuardarTaco = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lbTortilla10 = new javax.swing.JLabel();
        lbTotalTaco = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lbIdTacos = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSalsa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));

        lbTortilla6.setBackground(new java.awt.Color(255, 102, 0));
        lbTortilla6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTortilla6.setText("TORTILLA");

        opcSimple.setBackground(new java.awt.Color(255, 255, 153));
        opcSimple.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        opcSimple.setText("SIMPLE");
        opcSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSimpleActionPerformed(evt);
            }
        });

        opcDoble.setBackground(new java.awt.Color(255, 255, 102));
        opcDoble.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        opcDoble.setText("DOBLE");
        opcDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcDobleActionPerformed(evt);
            }
        });

        comboTortilla.setBackground(new java.awt.Color(153, 153, 255));
        comboTortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTortillaActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 255, 0));

        tblTortilla.setBackground(new java.awt.Color(51, 255, 51));
        tblTortilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTortilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTortillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTortilla);
        if (tblTortilla.getColumnModel().getColumnCount() > 0) {
            tblTortilla.getColumnModel().getColumn(0).setResizable(false);
            tblTortilla.getColumnModel().getColumn(1).setResizable(false);
            tblTortilla.getColumnModel().getColumn(2).setResizable(false);
            tblTortilla.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TACOS ALMACENADOS");

        txtIdTaco.setBackground(new java.awt.Color(102, 102, 255));

        btnBuscarTaco.setBackground(new java.awt.Color(0, 153, 153));
        btnBuscarTaco.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnBuscarTaco.setText("BUSCAR");
        btnBuscarTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTacoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 204, 204));
        btnModificar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(102, 255, 204));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alimentos_1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alimentos_1.jpg"))); // NOI18N

        lbTortilla3.setBackground(new java.awt.Color(0, 255, 0));
        lbTortilla3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTortilla3.setText("ALIMENTOS");

        comboAlimentos.setBackground(new java.awt.Color(51, 255, 0));
        comboAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlimentosActionPerformed(evt);
            }
        });

        tblAlimentos.setBackground(new java.awt.Color(255, 255, 51));
        tblAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlimentosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAlimentos);

        lbTortilla4.setBackground(new java.awt.Color(102, 204, 0));
        lbTortilla4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTortilla4.setText("SALSA");

        comboSalsa.setBackground(new java.awt.Color(255, 204, 0));
        comboSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSalsaActionPerformed(evt);
            }
        });

        btnTacoEconomico.setBackground(new java.awt.Color(255, 0, 0));
        btnTacoEconomico.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnTacoEconomico.setText("TACO ECONOMICO");
        btnTacoEconomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacoEconomicoActionPerformed(evt);
            }
        });

        btnTacoCaro.setBackground(new java.awt.Color(255, 51, 0));
        btnTacoCaro.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnTacoCaro.setText("TACO CARO");
        btnTacoCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacoCaroActionPerformed(evt);
            }
        });

        btnTacoPromedio.setBackground(new java.awt.Color(255, 102, 102));
        btnTacoPromedio.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnTacoPromedio.setText("TACO PROMEDIO");
        btnTacoPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTacoPromedioActionPerformed(evt);
            }
        });

        btnGuardarTaco.setBackground(new java.awt.Color(255, 204, 204));
        btnGuardarTaco.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnGuardarTaco.setText("GUARDAR TACO");
        btnGuardarTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTacoActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(255, 0, 204));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbTortilla10.setBackground(new java.awt.Color(255, 153, 0));
        lbTortilla10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTortilla10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTortilla10.setText("TOTAL TACOS");

        lbTotalTaco.setBackground(new java.awt.Color(51, 255, 51));
        lbTotalTaco.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lbTotalTaco.setText("00.00");

        btnVolver.setBackground(new java.awt.Color(255, 0, 51));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lbIdTacos.setBackground(new java.awt.Color(102, 255, 102));
        lbIdTacos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        btnInfo.setBackground(new java.awt.Color(51, 51, 255));
        btnInfo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnInfo.setText("INFORMACION");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        tblSalsa.setBackground(new java.awt.Color(255, 153, 0));
        tblSalsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSalsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalsaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSalsa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lbTortilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lbTortilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(336, 336, 336)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(lbIdTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(lbTortilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 11, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbTortilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbTotalTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcSimple)
                                .addGap(39, 39, 39)
                                .addComponent(opcDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTortilla, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdTaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscarTaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTacoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnTacoCaro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTacoPromedio)
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardarTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTortilla6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(opcSimple)
                                    .addComponent(opcDoble))
                                .addGap(9, 9, 9)
                                .addComponent(comboTortilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBuscarTaco)
                                    .addComponent(txtIdTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbIdTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lbTortilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lbTortilla4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTacoEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTacoCaro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)))
                .addComponent(btnTacoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarTaco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTotalTaco)
                            .addComponent(lbTortilla10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSimpleActionPerformed
        if (tblTortilla.getRowCount() <= 1) {
            if (this.opcSimple.isSelected()) {
                this.opcDoble.setSelected(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tiene que BORRAR una tortilla para cambiar a la OPCIÓN SIMPLE, actualmente hay 2 tortillas en la tabla...", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            this.opcSimple.setSelected(false);
        }
             // TODO add your handling code here:
    }//GEN-LAST:event_opcSimpleActionPerformed

    private void opcDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcDobleActionPerformed
       if (this.opcDoble.isSelected()) {
            this.opcSimple.setSelected(false);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_opcDobleActionPerformed

    private void comboTortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTortillaActionPerformed
      if (this.opcDoble.isSelected()) {
            if (tblTortilla.getRowCount() <= 1) {
                cargarFilaDeTabla(tblTortilla, comboTortilla, dtmTortilla);
            } else {
                JOptionPane.showMessageDialog(null, "Tiene seleccionada la opción DOBLE, por tanto, NO puede agregar más de 2 TORTILLAS!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            }
        } else if (opcSimple.isSelected()) {
            if (tblTortilla.getRowCount() <= 0) {
                cargarFilaDeTabla(tblTortilla, comboTortilla, dtmTortilla);
            } else {
                JOptionPane.showMessageDialog(null, "Tiene seleccionada la opción SIMPLE, por tanto, sólo puede AGREGAR 1 TORTILLA!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            }
        }        
    }//GEN-LAST:event_comboTortillaActionPerformed

    private void tblTortillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTortillaMouseClicked
        if (evt.getClickCount() == 2) { //si hace dos clicks se borra la fila de la tabla
            //String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tblTortilla.getValueAt(tblTortilla.getSelectedRow(), 2).toString()));
            //lbTotalTaco.setText(total_tacos);
            //dtmTortilla.removeRow(tblTortilla.getSelectedRow());
            eliminarFilaDeTabla(dtmTortilla, tblTortilla);

            
            if (tblTortilla.getRowCount() == 1) {
                this.opcSimple.setSelected(true);
                this.opcDoble.setSelected(false);
            }
            
        }         // TODO add your handling code here:
    }//GEN-LAST:event_tblTortillaMouseClicked

    private void btnBuscarTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTacoActionPerformed
       try {
            int idtacoBuscado = Integer.parseInt(txtIdTaco.getText());
            //controladortaco.buscarTaco(idtacoBuscado, dtmTortilla, dtmSalsa, dtmAlimento, tblTortilla, tblAlimentos, tblSalsa);
            controladortaco.buscarTaco(idtacoBuscado, dtmTortilla, dtmSalsa, dtmAlimento, tblTortilla, tblAlimentos, tblSalsa);
            //for (int i = 0; i < 2; i++) {
                //System.out.println("id array: " + arrayy[i]);
            //}

            double importe = controladortaco.obtenerImporteAlRealizarBusqueda(idtacoBuscado);
            if (importe == 0.0) {
                JOptionPane.showMessageDialog(null, "El Taco N° " + idtacoBuscado + " NO EXISTE!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(false);
            }
            else{
               String importeS = String.valueOf(importe);
               //System.out.println("importe string:" + importeS);
               lbTotalTaco.setText(importeS);
               btnEliminar.setEnabled(true);
               btnModificar.setEnabled(true);
            }
            

            if (dtmTortilla.getRowCount() == 2) {
                this.opcSimple.setSelected(false);
                this.opcDoble.setSelected(true);
            } else {
                this.opcSimple.setSelected(true);
                this.opcDoble.setSelected(false);
            }
            

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un N° de TACO en el buscador!!", "ERROR", JOptionPane.ERROR_MESSAGE);  
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarTacoActionPerformed

    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            double importe = Double.parseDouble(lbTotalTaco.getText());

            int idtacoBuscado = Integer.parseInt(txtIdTaco.getText());

            if(controladortaco.modificarTaco(idtacoBuscado, dtmTortilla, importe, dtmAlimento, dtmSalsa)==true){
                limpiarTablas();
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(false);
            }
            
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un N° de TACO en el buscador!!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }                                            
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int idtacoBuscado = Integer.parseInt(txtIdTaco.getText());
            controladortaco.eliminarTaco(idtacoBuscado);
            txtIdTaco.setText("");
            numeroDeTacosAlmacenados();
            limpiarTablas();
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Ingrese un N° de TACO en el buscador para poder ELIMINARLO!!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void comboAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlimentosActionPerformed
        if (tblAlimentos.getRowCount() <= 4) {
            cargarFilaDeTabla(tblAlimentos, comboAlimentos, dtmAlimento);
        } 
        else {
            JOptionPane.showMessageDialog(null, "Sólo puede agregar hasta 5 ALIMENTOS como MÁXIMO!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_comboAlimentosActionPerformed

     private void limpiarTablas() {
        this.dtmTortilla.setRowCount(0);
        this.dtmAlimento.setRowCount(0);
        this.dtmSalsa.setRowCount(0);
        lbTotalTaco.setText("0.0");
        comboAlimentos.setSelectedItem("<Seleccione>");
        comboTortilla.setSelectedItem("<Seleccione>");
        comboSalsa.setSelectedItem("<Seleccione>");
        txtIdTaco.setText("");

    }

     private void cargarFilaDeTabla(JTable tabla, JComboBox combobox, DefaultTableModel dtm) {
        String Lista = (String) combobox.getSelectedItem();
        if ("<Seleccione>" != combobox.getSelectedItem()) {
            String[] Registro = Lista.split("_");
            dtm.addRow(new Object[]{Registro[0], Registro[1], Registro[2]});

            tabla.setModel(dtm);
            String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) + Double.valueOf(Registro[2]));
            lbTotalTaco.setText(total_tacos);
        }
    }
   
    private void tblAlimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlimentosMouseClicked
       if (evt.getClickCount() == 2) { //si hace dos clicks se borra la fila de la tabla
            //String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tblAlimentos.getValueAt(tblAlimentos.getSelectedRow(), 2).toString()));
            //lbTotalTaco.setText(total_tacos);
            //dtmAlimento.removeRow(tblAlimentos.getSelectedRow());
            //tblAlimentos.setModel(dtmAlimento); 
            eliminarFilaDeTabla(dtmAlimento, tblAlimentos);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_tblAlimentosMouseClicked

    private void comboSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSalsaActionPerformed
         if (tblSalsa.getRowCount() < 1) {
            cargarFilaDeTabla(tblSalsa, comboSalsa, dtmSalsa);
        }
         else {
            JOptionPane.showMessageDialog(null, "Sólo puede agregar una SALSA como MÁXIMO!!!", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboSalsaActionPerformed

    private void btnTacoEconomicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacoEconomicoActionPerformed
        //controladortaco.llenarTablaTortillaEconomica(dtmTortilla, tblTortilla);
        dtmSalsa.setRowCount(0);
        controladortaco.generarTacoMasEconomico(dtmTortilla, tblTortilla, dtmAlimento, tblAlimentos);
        
        //controladortaco.llenarTablaAlimentoEconomico(dtmAlimento, tblAlimentos);
        double importe = Double.parseDouble(tblTortilla.getValueAt(0, 2).toString()) + Double.parseDouble(tblAlimentos.getValueAt(0, 2).toString());
        String val = String.valueOf(importe);
        lbTotalTaco.setText(val);
        this.opcSimple.setSelected(true);
        this.opcDoble.setSelected(false);
       
    }//GEN-LAST:event_btnTacoEconomicoActionPerformed

    private void btnTacoCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacoCaroActionPerformed
        controladortaco.generarTacoMasCaro(dtmTortilla, tblTortilla, dtmAlimento, tblAlimentos, dtmSalsa, tblSalsa); //FUNCIONA SEGUIR CON LOS DEMAS

        double importe = (Double.parseDouble(tblTortilla.getValueAt(0, 2).toString()) * 2) + (Double.parseDouble(tblAlimentos.getValueAt(0, 2).toString()) * 5) + Double.parseDouble(tblSalsa.getValueAt(0, 2).toString());
        String val = String.valueOf(importe);
        lbTotalTaco.setText(val);
        this.opcSimple.setSelected(false);
        this.opcDoble.setSelected(true);                                           
    
    }//GEN-LAST:event_btnTacoCaroActionPerformed

    private void btnTacoPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacoPromedioActionPerformed
        //double valorPromedioTaco = controladortaco.promedioTortillas() + controladortaco.promedioAlimentos() + controladortaco.promedioSalsas();
        //String mensaje = "Promedio de Tortillas = " + controladortaco.promedioTortillas() + "\nPromedio de Alimentos = " + controladortaco.promedioAlimentos() + "\nPromedio de Salsas = " + controladortaco.promedioSalsas() + "\nPromedio de Taco Completo = " + valorPromedioTaco;
        String mensaje = "Valor promedio de un TACO COMPLETO = " + controladortaco.obtenerValorPromedioTacoCompleto();
        JOptionPane.showMessageDialog(null, mensaje);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTacoPromedioActionPerformed

    private void btnGuardarTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTacoActionPerformed
       if (tblTortilla.getRowCount() == 1 && this.opcDoble.isSelected()) {
            this.opcSimple.setSelected(true);
            this.opcDoble.setSelected(false);
        }
        double importe = Double.parseDouble(lbTotalTaco.getText());
        //System.out.println("importe: " + importe);
        controladortaco.agregarTaco(importe, dtmTortilla, dtmSalsa, dtmAlimento);
        numeroDeTacosAlmacenados();
        limpiarTablas();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarTacoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiarTablas();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose(); //para que se cierre la actual:                            // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoActionPerformed

    private void tblSalsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalsaMouseClicked
         if (evt.getClickCount() == 2) { //si hace dos clicks se borra la fila de la tabla
            //String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tblSalsa.getValueAt(tblSalsa.getSelectedRow(), 2).toString()));
            //lbTotalTaco.setText(total_tacos);
            //dtmSalsa.removeRow(tblSalsa.getSelectedRow());
            //tblSalsa.setModel(dtmSalsa);
            eliminarFilaDeTabla(dtmSalsa, tblSalsa);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblSalsaMouseClicked

    private void estiloFrmTaco() {
        Color verdeAgua = new Color(173, 255, 139);
        this.getContentPane().setBackground(verdeAgua);
        this.setResizable(false);
    }

    private void numeroDeTacosAlmacenados() {
        int cantidad = controladortaco.obtenerCantidadTacosGenerados();
        //int id = controladortaco.llevoidallabel(WIDTH)
        String cantidadS = String.valueOf(cantidad);
        lbIdTacos.setText(cantidadS);
    }

     private void estiloTablas(DefaultTableModel dtm, JTable tabla) {
        String[] titulos = new String[]{"Código", "Nombre", "Precio $$$"}; //titulos de la tabla
        dtm.setColumnIdentifiers(titulos);

        tabla.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12));
        JTableHeader th;
        th = tabla.getTableHeader();
        th.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14));

        tabla.setModel(dtm);

    }

      private void eliminarFilaDeTabla(DefaultTableModel dtm, JTable tabla) {
        String total_tacos = Double.toString(Double.valueOf(lbTotalTaco.getText()) - Double.valueOf(tabla.getValueAt(tabla.getSelectedRow(), 2).toString()));
        lbTotalTaco.setText(total_tacos);
        dtm.removeRow(tabla.getSelectedRow());
        tabla.setModel(dtm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTaco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTaco().setVisible(true);
            }
        });
        
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTaco;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarTaco;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnTacoCaro;
    private javax.swing.JButton btnTacoEconomico;
    private javax.swing.JButton btnTacoPromedio;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboAlimentos;
    private javax.swing.JComboBox<String> comboSalsa;
    private javax.swing.JComboBox<String> comboTortilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbIdTacos;
    private javax.swing.JLabel lbTortilla10;
    private javax.swing.JLabel lbTortilla3;
    private javax.swing.JLabel lbTortilla4;
    private javax.swing.JLabel lbTortilla6;
    private javax.swing.JLabel lbTotalTaco;
    private javax.swing.JRadioButton opcDoble;
    private javax.swing.JRadioButton opcSimple;
    private javax.swing.JTable tblAlimentos;
    private javax.swing.JTable tblSalsa;
    private javax.swing.JTable tblTortilla;
    private javax.swing.JTextField txtIdTaco;
    // End of variables declaration//GEN-END:variables
}
