
package vistas;

import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author gerardo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public  MenuPrincipal() {
        initComponents();
         this.setResizable(false);
        Color naranja=new Color(255, 102, 51); 
        this.getContentPane().setBackground(naranja);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAlimentos = new javax.swing.JMenuItem();
        itemSalsa = new javax.swing.JMenuItem();
        itemTortilla = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemGenerarTaco = new javax.swing.JMenuItem();
        jMenuTacoEconomico = new javax.swing.JMenuItem();
        jMenuTacoCaro = new javax.swing.JMenuItem();
        jMenuTacoPromedio = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/images (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        lbTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("FOOD TAQUERIA");

        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("ELEGIR INGREDIENTES");
        jMenu1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        itemAlimentos.setText("Alimentos");
        itemAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAlimentosActionPerformed(evt);
            }
        });
        jMenu1.add(itemAlimentos);

        itemSalsa.setText("Salsas");
        itemSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalsaActionPerformed(evt);
            }
        });
        jMenu1.add(itemSalsa);

        itemTortilla.setText("Tortillas");
        itemTortilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTortillaActionPerformed(evt);
            }
        });
        jMenu1.add(itemTortilla);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("TACOS");
        jMenu3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        itemGenerarTaco.setText("Generar taco");
        itemGenerarTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGenerarTacoActionPerformed(evt);
            }
        });
        jMenu3.add(itemGenerarTaco);

        jMenuTacoEconomico.setText("Taco economico");
        jMenuTacoEconomico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTacoEconomicoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuTacoEconomico);

        jMenuTacoCaro.setText("Taco caro");
        jMenuTacoCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTacoCaroActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuTacoCaro);

        jMenuTacoPromedio.setText("Taco Promedio");
        jMenuTacoPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTacoPromedioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuTacoPromedio);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         int salida = JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir??", "???", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (salida == 0) {
                JOptionPane.showMessageDialog(null, "Hasta luego!!\nTacoTito's Foodtacos");
                this.dispose();
            }
     // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void itemGenerarTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGenerarTacoActionPerformed
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemGenerarTacoActionPerformed

    private void itemAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAlimentosActionPerformed
         FrmAlimento frmalimento = new FrmAlimento();
        frmalimento.setVisible(true);
        this.dispose(); //para que se cierre la actual
   
    }//GEN-LAST:event_itemAlimentosActionPerformed

    private void itemSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalsaActionPerformed
        FrmSalsa frmsalsa = new FrmSalsa();
        frmsalsa.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemSalsaActionPerformed

    private void itemTortillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTortillaActionPerformed
       FrmTortilla frmtortilla = new FrmTortilla();
        frmtortilla.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_itemTortillaActionPerformed

    private void jMenuTacoEconomicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTacoEconomicoActionPerformed
        JOptionPane.showMessageDialog(null, "A continuación se abrirá una ventana donde en la parte inferior hacia la derecha, encontrará un botón para ver el taco más económico...");
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_jMenuTacoEconomicoActionPerformed

    private void jMenuTacoCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTacoCaroActionPerformed
        JOptionPane.showMessageDialog(null, "A continuación se abrirá una ventana donde en la parte inferior hacia la derecha, encontrará un botón para ver el taco más caro...");
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual
    }//GEN-LAST:event_jMenuTacoCaroActionPerformed

    private void jMenuTacoPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTacoPromedioActionPerformed
         JOptionPane.showMessageDialog(null, "A continuación se abrirá una ventana donde en la parte inferior hacia la derecha, encontrará un botón para ver el valor promedio de un taco completo...");
        FrmTaco frmtaco = new FrmTaco();
        frmtaco.setVisible(true);
        this.dispose(); //para que se cierre la actual                                                                            

    }//GEN-LAST:event_jMenuTacoPromedioActionPerformed

                                                                        

   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
        
         try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem itemAlimentos;
    private javax.swing.JMenuItem itemGenerarTaco;
    private javax.swing.JMenuItem itemSalsa;
    private javax.swing.JMenuItem itemTortilla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuTacoCaro;
    private javax.swing.JMenuItem jMenuTacoEconomico;
    private javax.swing.JMenuItem jMenuTacoPromedio;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
